### ISSUE TITLE
ImportError: cannot import name iio

### ISSUE THREAD

**Issue by drom** [analogdevicesinc/gr-iio#11]
OpenSuSe Tumbleweed.
Followed install instruction on https://wiki.analog.com/resources/tools-software/linux-software/gnuradio

Instantiated Pluto Source --> Qt GUI Frequency Sink
F5 --> Ok
F6 -->
```sh
Executing: /usr/bin/python2 -u /home/drom/work/github/drom/pluto/top_block.py

Traceback (most recent call last):
  File "/home/drom/work/github/drom/pluto/top_block.py", line 22, in <module>
    from gnuradio import iio
ImportError: cannot import name iio
```

**Comment by tfcollins** [comment]
What happens when you run "import gnuradio.iio" from a python terminal?

**Comment by pcercuei** [comment]
I think you need to compile and install gr-iio with -DCMAKE_INSTALL_PREFIX=/usr, otherwise the Python scripts will not be found by the Python runtime, as it does not search in /usr/local by default.

**Comment by drom** [comment]
@pcercuei Thank you very much. It works.
Does it mean the change in instruction? or it is just my case?

**Comment by pcercuei** [comment]
I think the instructions could be changed, yes.

**Comment by tfcollins** [comment]
Updated the wiki for this case: https://wiki.analog.com/resources/tools-software/linux-software/gnuradio?&#compiling_the_gr-iio_blocks_for_your_pc

**Comment by mhennerich** [comment]
Please approve wiki pages after updating them. If for some reason you can't approve them please let me know. I approved this one for you.
