### ISSUE TITLE
FMComms 2/3/4 is not working with GNURadio v3.11.0.0git-3-g3349d483

### ISSUE THREAD

**Issue by nicolasflorio1** [analogdevicesinc/gr-iio#114]
I'm usung Ubuntu 20.4 and compiled GNURadio v3.11.0.0git-3-g3349d483 from source. 
When I try to use FMComms 2/3/4 I got the following message:

(NameError("'len_tag_key' is not defined")

So I added:

-   id: len_tag_key
    label: Packet Length Tag
    dtype: string
    default: packet_len
    hide: part

To the file: iio_fmcomms2_source.block.yml

But now I'm getting the following error message: 
  "NameError: name 'rx1_en' is not defined"

**Comment by tfcollins** [comment]
This was already fixed by https://github.com/gnuradio/gnuradio/commit/b44e28a8e5041dcb22812a8c514bcc0d88857150

Please upgrade to a newer branch/tag or cherry-pick that commit.
