### ISSUE TITLE
FMComms2 Type description error in  iio_fmcomms2_source.block.yml

### ISSUE THREAD

**Issue by MountainLogic** [analogdevicesinc/gr-iio#119]
WHen using iio_fmcomms2_source block in radio conda version 3.10.3.0 (Python 3.10.8) there is a mismatch between the type selected in the parameters dialog and the color/type of the  output port.  When complex F32 is selected the port color is orange and when int15 is selected the port color is blue.  GRC only allows connections with this iio block when connected to a block with the same color, regardless of the mismatch with the parameter in the properties dialog. The section of the yml file for the block is as follows:

`
parameters:
-   id: type
    label: Output Type
    dtype: enum
    options: [fc32, sc16]
    option_labels: [int16, Complex float32, Complex int16]
    option_attributes:
        type: [fc32, sc16]
    hide: part
``

I assume that type lint and option labels list length should match?

![GNUcapture](https://github.com/analogdevicesinc/gr-iio/assets/13784198/4b45690f-96a3-432a-8c1c-be4059994f59)

**Comment by tfcollins** [comment]
3.10+ support is all in mainline gr now and this issue is already fixed there. Not sure how new the conda build are or if you can pull in patches. Anyway you probably need to reach out to the radioconda team or switch to gr source builds to get the fix
