### ISSUE TITLE
Shared context get destroyed too early

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/gr-iio#20]
If a context is shared between blocks it should destroy only by the last running block using it.

**Comment by rgetz** [comment]
and this is primarily due to libiio not keeping track of it's own users, and forcing everyone to do their own context manager (since we don't want to add the requirement for atomic operations (ie boost) in libiio)?

**Comment by lclausen-adi** [comment]
We have platform independent mutual exclusion support in libiio (https://github.com/analogdevicesinc/libiio/blob/master/lock.c). That's not the problem.

**Comment by rgetz** [comment]
so, why do we want to avoid counting references to a context then? (sorry if we went over this before).

**Comment by tfcollins** [comment]
This was part of a bug we fixed awhile ago (https://github.com/analogdevicesinc/gr-iio/issues/4). However, when the contexts were being destroyed it needs to be done in a specific order.  Basically the last block with it open needs to do the destroying.
