### ISSUE TITLE
how to get data through 9361?

### ISSUE THREAD

**Issue by VIRUSOLDLIu** [analogdevicesinc/gr-iio#52]
hi!
I wonder in which way do the fmcomms2 source block operate on the ad9361. 
how can the block control the ad9361 to start its tx or rx , activoate its channel or buffer or something else? we can find some functions on libiio to control them ,but i did not
 recognize them on gnuradio. so where can i get the function or mechanism of fmcomms2 block to operate the 9361? 
thank you?

**Comment by tfcollins** [comment]
The blocks in gr-iio utilize the IIO drivers through remote or local contexts through the specified URIs in the block APIs: https://wiki.analog.com/resources/tools-software/linux-software/gnuradio#using_the_fmcomms-234_blocks
 
The blocks are implemented so you can almost ignore the aspects of libIIO and just do things through standard GNU Radio APIs.

**Comment by tfcollins** [comment]
Assuming this is resolved.
