### ISSUE TITLE
upgrade-3.8 tuning parameter freezes program

### ISSUE THREAD

**Issue by paulgrahek** [analogdevicesinc/gr-iio#70]
After installing gr-iio with Python 3 for GNU-Radio 3.8, updating parameter in PlutoSDR Source block gives the following output then freezes the program:
```
thread[thread-per-block[0]: <block fmcomms2_source(8)>]: pmt_to_long: wrong_type : #f
```
OS: Pop! OS 19.10

**Comment by tfcollins** [comment]
Which gr-iio branch are you using? Are you updating a parameter at runtime? and which parameter?

-Travis

**Comment by paulgrahek** [comment]
Branch: upgrade-3.8
Tuning any of frequency, sample rate, bandwidth, or gain throws this error for me. Error persists even if I have it to where only one of these is tunable.

**Comment by tfcollins** [comment]
PR should fix those issues: https://github.com/analogdevicesinc/gr-iio/pull/71
